version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    assignees:
      - "un33k"
    reviewers:
      - "un33k"
    labels:
      - "dependencies"
      - "automated"
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "vitest*"
          - "typescript"
          - "tsx"
      production-dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "@types/*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "04:00"
    assignees:
      - "un33k"
    reviewers:
      - "un33k"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"