blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/ehaye/stts/discussions
    about: Please ask and answer questions in GitHub Discussions
  - name: Security Issues
    url: https://github.com/ehaye/stts/security/advisories/new
    about: Please report security vulnerabilities via private disclosure