name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (patch, minor, major, or auto)'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - patch
          - minor
          - major
  # Optional: Uncomment to enable release branch pattern
  # push:
  #   branches:
  #     - release

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Validate package
        run: npm run validate

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ "${{ github.event.inputs.release-type }}" != "auto" ] && [ "${{ github.event.inputs.release-type }}" != "" ]; then
            npx semantic-release --no-ci --force-release=${{ github.event.inputs.release-type }}
          else
            npx semantic-release
          fi
